# ABCD行列を用いたレンズ設計

In [1]:
import numpy as np

## ABCD行列の定義

In [2]:
def abcd_refraction(n1,n2,r):
    ans = np.array([[1,0],[1/r * (n1/n2 -1),n1/n2]])
    return np.round(ans,4)

def abcd_straight(d):
    ans = np.array([[1,d],[0,1]])
    return np.round(ans,4)

def abcd_lens(n1,n2,r1,r2,d):
    ans = abcd_refraction(n2,n1,r2) @ abcd_straight(d) @ abcd_refraction(n1,n2,r1)
    return np.round(ans,4)

In [3]:
# 出力例
print(abcd_refraction(1,1.5,100000))
print(abcd_straight(2))
abcd_lens(1,1.5,-1,2,0)

[[ 1.      0.    ]
 [-0.      0.6667]]
[[1 2]
 [0 1]]


array([[1.  , 0.  ],
       [0.75, 1.  ]])

## 薄いレンズのとき
薄いレンズのときのときは，$d=0$とすればよい．
\begin{eqnarray}
	\left(\begin{array}{cc}1&0\\C_1 + C_2 &1\end{array}\right)
	=\left(\begin{array}{cc}1&0\\C_1 &1\end{array}\right)
	\left(\begin{array}{cc}1&0\\C_2 &1\end{array}\right)
\end{eqnarray}

であるからレンズを重ね合わせると新たにできたレンズの焦点距離は，２レンズの焦点距離の逆数の和に等しい．つまりレンズを重ね合わせると焦点距離は短くなる(２レンズの焦点距離が正のとき)．
２レンズの焦点距離を長くしたいときは，例えば"→))","→((","→)("のような形のレンズ)

In [4]:
abcd_lens(1,1.5,2,-2,0) @ abcd_lens(1,1.5,2,-2,0) @ abcd_lens(1,1.5,1,-1,0.0)

array([[ 1.,  0.],
       [-2.,  1.]])

In [5]:
abcd_lens(1,1.5,-1,-2,0) @ abcd_lens(1,1.5,-1,-2,0)

array([[1. , 0. ],
       [0.5, 1. ]])